created-connect-wallet-modal (готово)
AndreiBelokopytov/magnetar pull request #1
Opened 2021-11-27 16:38 UTC by ValesValesskiy

2021-11-27 18:02 UTC, AndreiBelokopytov requested changes
По возможности перенести в тему все стили. 
Компонент `Button` пока не нужно создавать. 
Использовать `Card` для кликабельной области в диалоге подключения кошелька.

2021-11-27 20:56 UTC, ValesValesskiy commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +        style={
Не совсем понимаю как добавить box-shadow для primary. Цвет в теме нашёл как accent-1. Но именно добавить свойство для primary, пока не понимаю как.

2021-11-27 22:33 UTC, ValesValesskiy commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +          <Text weight={600} margin={"-24px 0 24px 0"} style={{fontSize: "20px"}}>
Двадцатипиксельного шрифта не заявлено в дизайне. Использовать ближайший, восемнадцать пикселей?

2021-11-28 07:26 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +          <Text weight={600} margin={"-24px 0 24px 0"} style={{fontSize: "20px"}}>
Да, дизайнер забыл поменять шрифты

2021-11-29 09:22 UTC, AndreiBelokopytov requested changes
Использовать атрибуты вместо стилей.
Использовать атрибут `variant` для компонента `Text`.
Привести отступы в модалке в соответствие с дизайном.
Откатить изменения стилей `Button`.

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +            backgroundColor: normalizeColor("dark-2", theme),
Стили нужно перенести в тему (создать стили для Layer)

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                    borderRadius: "16px"
использовать атрибут `round`

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +            <Card style={{width: "100%", backgroundColor: normalizeColor("dark-1", theme)}} onClick={!isMetaMaskConnecting ? handleConnectMetaMask : undefined}>
Использовать атрибуты `background`, `width`

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                        color: normalizeColor("light-2", theme)
использовать атрибут `color`

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/theme/defaultTheme.ts
> +    primary: {
Данная задача не предполагает изменение стилей Button (дизайнер еще не добавил цвета в тему). Данные изменения нужно откатить.

2021-11-29 09:22 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +        <Box direction={"column"} align={"center"} justify={"start"}>
Задать отступы, соответствующие дизайну

2021-11-29 16:45 UTC, ValesValesskiy commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +            <Card style={{width: "100%", backgroundColor: normalizeColor("dark-1", theme)}} onClick={!isMetaMaskConnecting ? handleConnectMetaMask : undefined}>
Работает странно через атрибуты. Оставил style пока что для backgroundColor. Остаются ховеры и цвет не переопределяется.

2021-11-29 18:25 UTC, AndreiBelokopytov requested changes
Поправить цвета.
Заменить `Text` на `Heading`.

2021-11-29 18:25 UTC, AndreiBelokopytov commented on src/theme/defaultTheme.ts
> +    background: "#202632",
цвет нужно взять из темы

2021-11-29 18:25 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                    color={normalizeColor("light-2", theme)}
`normalizeColor` не нужно, в атрибут передается строка

2021-11-29 18:25 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                    color={normalizeColor("light-2", theme)}
 В дизайне  цвет `light-3`

2021-11-29 18:25 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                  <Text size={"large"}>
А цвет?

2021-11-29 18:25 UTC, AndreiBelokopytov commented on src/components/WalletSelectionModal/WalletSelectionModal.tsx
> +                  <Text size={"large"}>
Вместо `Text`  нужен `Heading`, дизайнер обновил макет

2021-11-30 15:46 UTC, AndreiBelokopytov approved these changes

2021-11-30 15:48 UTC, AndreiBelokopytov commented
Fix wallect connect modal styles (PR #1 )

2021-11-30 15:50 UTC, merged