added-LocalStorageStore (готово)
AndreiBelokopytov/magnetar pull request #7
Opened 2021-12-10 02:29 UTC by ValesValesskiy

2021-12-10 08:22 UTC, AndreiBelokopytov requested changes
Использовать для сериализации `JSON.parse`, `JSON.stringify`.
Добавить `LocalStorageAdapter` в контейнер зависимостей Inversify.
Убрать состояние из `LocalStorageAdapter`.

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/adapters/wallet/WalletAdapterDelegate.impl.ts
> +    this._accountInfoStore.refresh();
Задача конструктора – инициализировать объект. Сайд-эффектов в нем быть не должно, это очень плохой паттерн.

Представь, например, если бы конструктор `Date` выполнял синхронизацию с мировым временем. Насколько бы программист удивился, увидев кучу запросов к серверу в своей программе для каждого созданного объекта `Date`.

Любой запрос к внешнему API в программе должен запускаться явно, когда это определил программист.

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/providers/LocalStorageProvider.ts
> +export class LocalStorageProvider<T extends Stringify, R> implements PersistentStorageProvider<T, undefined, R> {
Нет необходимости в новом интерфейсе.
`T extends object`, потому что метод `toString` есть в прототипе объекта.

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/providers/PersistentStorageProvider.ts
> +    fetch(request?: Request): Promise<void>;
нужно, чтобы `fetch` возвращал значение
я накосячил, прислал некорректный интерфейс

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/providers/LocalStorageProvider.ts
> +export class LocalStorageProvider<T extends Stringify, R> implements PersistentStorageProvider<T, undefined, R> {
нужно, чтобы этот класс можно было инжектировать с помощью Inversify

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +  _addressStorage: LocalStorageProvider<string, AccountInfo>;
нужно сделать параметром конструктора и инжектировать с помощью `Inversify`

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/providers/LocalStorageProvider.ts
> +export class LocalStorageProvider<T extends Stringify, R> implements PersistentStorageProvider<T, undefined, R> {
вместо того, чтобы использовать `toString` для сериализации, лучше взять `JSON.stringify` и `JSON.parse`. Тогда можно будет сохранять в `localStorage` любоой объект

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +    this._addressStorage.update(`${walletType}:${address}`);
использовать `JSON.stringify` (вынести в `LocalStorageProvider`)

2021-12-10 08:22 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +      const accountInfo = data.split(':');
использовать `JSON.parse` (вынести в `LocalStorageProvider`)

2021-12-10 08:24 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +      const accountInfo = data.split(':');
опять же, не делать таких вещей в конструкторе, вынести в отдельный метод

2021-12-10 08:44 UTC, ValesValesskiy commented on src/providers/LocalStorageProvider.ts
> +export class LocalStorageProvider<T extends Stringify, R> implements PersistentStorageProvider<T, undefined, R> {
Ну я так делал сначала, кстати, потом решил переделать через toString()  - метод.

2021-12-10 19:48 UTC, AndreiBelokopytov requested changes
Разобраться с добавлением фабрики в контейнер зависимостей.
Добавить в `AccountInfo` метод для сериализации в объект.

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +      this.setAccountInfo(walletType as WalletType, address);
В `AccountInfo` нужен конструктор, который принимает объект

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +    this._addressProvider.update({ walletType, address });
В `AccountInfo` нужен метод `toJSON` или `asObject`, который возвращает сериализуемые поля

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +type AccountInfoFields = {
это должен быть тип параметров конструктора `AccountInfo`

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/stores.module.ts
> +  bind<PersistentStorageProvider<any>>(LocalStorageProvider).toFactory<LocalStorageProviderImpl<any>>(() => {
ошибка TypeScript. Пример фабрики смотреть в `adapterModule`

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +    @inject(LocalStorageProvider) _addressProviderFactory: <AccountInfoFields>(key: string) => LocalStorageProviderImpl<AccountInfoFields>
использование `LocalStorageProviderImpl` убивает весь смысл инверсии зависимостей. Классы снова сильно связаны друг с другом. Здесь должен использоваться интерфейс, а не конкретный класс.
Статья для понимания https://www.martinfowler.com/ieeeSoftware/coupling.pdf

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/providers/LocalStorageProvider.ts
> +export const LocalStorageProvider = Symbol("LocalStorageProvider");
Нет константы для фабрики?

2021-12-10 19:48 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +    @inject(LocalStorageProvider) _addressProviderFactory: <AccountInfoFields>(key: string) => LocalStorageProviderImpl<AccountInfoFields>
добавить private readonly

2021-12-17 18:23 UTC, AndreiBelokopytov commented on src/stores/AccountInfoStore.impl.ts
> +  @observable
не исправлено

2021-12-28 11:30 UTC, merged